# Generated by Django 2.2.6 on 2020-05-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invenjtario',
            new_name='Inventario',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Direccion',
            new_name='direccion',
        ),
    ]
