# Generated by Django 2.2.6 on 2020-05-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_auto_20200520_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_Defectuosos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.PositiveIntegerField(default=0, verbose_name='Existencia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Producto')),
            ],
            options={
                'verbose_name': 'Inventario De Productos Defectuosos',
                'verbose_name_plural': 'Inventario De Productos Defectuosos',
                'db_table': 'inventario_defectuosos',
            },
        ),
        migrations.CreateModel(
            name='DevolucionesDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('fecha_de_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Cliente')),
            ],
            options={
                'verbose_name': 'Devoluciones de Ventas',
                'verbose_name_plural': 'Devoluciones de Ventas',
                'db_table': 'decoluciones_de_venta',
            },
        ),
        migrations.CreateModel(
            name='DevolucionDeCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('fecha_de_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('numero_factura', models.PositiveIntegerField(help_text='Solo Incluir Numeros', verbose_name='Número de Factura')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Total')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Proveedor')),
            ],
            options={
                'verbose_name': 'Devolucion de Compras',
                'verbose_name_plural': 'Devoluciones de Compras',
                'db_table': 'devolucion_de_compra',
            },
        ),
        migrations.CreateModel(
            name='Devolucion_Proveedores_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('fecha_de_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('numero_factura', models.PositiveIntegerField(help_text='Solo Incluir Numeros', verbose_name='Número de Factura')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Total')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Proveedor')),
            ],
            options={
                'verbose_name': 'Devolucion a Proveedores de Productos Defectuosos',
                'verbose_name_plural': 'Devolucion a Proveedores de Productos Defectuosos',
                'db_table': 'devolucio_proveedores_d',
            },
        ),
        migrations.CreateModel(
            name='Devolucion_Clienes_Def',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Cliente')),
            ],
            options={
                'verbose_name': 'Devolucion de CLientes en Productos Defectuosos',
                'verbose_name_plural': 'Devolucion de CLientes en Productos Defectuosos',
                'db_table': 'devolucion_clientes_def',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionesDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Inventario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoluciones.DevolucionesDeVenta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDevolcionCLientesDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('devolucion_clientes_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoluciones.Devolucion_Clienes_Def')),
                ('inventario_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoluciones.Inventario_Defectuosos')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDevCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio Costo')),
                ('dev_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoluciones.DevolucionDeCompra')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Dev_Prov_Def',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio Costo')),
                ('dev_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoluciones.Devolucion_Proveedores_D')),
                ('inventario_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoluciones.Inventario_Defectuosos')),
            ],
        ),
    ]
