# Generated by Django 2.2.6 on 2020-05-26 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_auto_20200520_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('fecha_de_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('numero_factura', models.PositiveIntegerField(help_text='Solo Incluir Numeros', verbose_name='Número de Factura')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Total')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio Costo')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Compra')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Inventario')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'detalle_compra',
            },
        ),
    ]
